version: '3.3'

services:
  master:
      build:
        context: .
        args:
          MASTER_NODE: master
      entrypoint: ["/adampro/wait-for-it.sh", "cassandra:9042", "--", "/adampro/bootstrap.sh", "-d", "--masternode"]
      image: vitrivr/adampro-dist
      hostname: master
      depends_on:
        - cassandra
        - postgres
        - solr
      environment:
        ADAMPRO_DRIVER_MEMORY: 4g
        ADAMPRO_EXECUTOR_MEMORY: 2g
        SPARK_PUBLIC_DNS: localhost
      expose:
        - 7001
        - 7002
        - 7003
        - 7004
        - 7005
        - 7006
        - 7077
        - 6066
      ports:
        - 4040:4040
        - 5890:5890
        - 6066:6066
        - 7077:7077
        - 8020:8020
        - 8080:8080
        - 9099:9099
      volumes:
        - ./adampro.conf:/adampro/adampro.conf
        - ./shared/:/adampro/data/shared
      networks:
        - vitrivrnw

  worker:
      image: vitrivr/adampro-dist
      entrypoint: ["/adampro/wait-for-it.sh", "master:7077", "--", "/adampro/bootstrap.sh", "-d", "--workernode"]
      environment:
        SPARK_WORKER_INSTANCES: 1
        SPARK_PUBLIC_DNS: localhost
      depends_on:
        - master
      links:
        - master
      expose:
        - 7012
        - 7013
        - 7014
        - 7015
        - 7016
        - 8881
      ports:
        - 8081
      volumes:
        - ./adampro.conf:/adampro/adampro.conf
        - ./shared/:/adampro/data/shared
      networks:
        - vitrivrnw


  postgres:
      image: postgres:9.4
      environment:
        POSTGRES_USER: adampro
        POSTGRES_PASSWORD: adampro
        POSTGRES_DB: adampro
      hostname: postgres
      ports:
        - 5432:5432
      volumes:
        - ./shared/:/adampro/data/shared
      networks:
        - vitrivrnw

  solr:
      image: solr:7.1
      hostname: solr
      ports:
        - 8983:8983
      volumes:
        - ./shared/:/adampro/data/shared
      networks:
        - vitrivrnw

  cassandra:
      image: cassandra:3.11
      hostname: cassandra
      ports:
        - 9042:9042
      volumes:
        - ./shared/:/adampro/data/shared
      networks:
        - vitrivrnw

networks:
    vitrivrnw:
      driver: bridge
